### ISSUE TITLE
Pagure API sometimes returns 404

### ISSUE THREAD

**Issue by TomasTomecek** [packit/dist-git-to-source-git#221]
```
Traceback (most recent call last):
  File "/usr/local/bin/dist2src", line 11, in <module>
    load_entry_point('dist-git-to-source-git==0.1.dev1+g99614a9.d20210629', 'console_scripts', 'dist2src')()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/dist2src/cli.py", line 248, in check_updates
    Updater().check_updates(project, branch)
  File "/usr/local/lib/python3.6/site-packages/dist2src/worker/updater.py", line 69, in check_updates
    self._check_and_update_project(project_to_be_processed, branch=branch)
  File "/usr/local/lib/python3.6/site-packages/dist2src/worker/updater.py", line 99, in _check_and_update_project
    for branch, commit in self._get_out_of_date_branches(project, branch):
  File "/usr/local/lib/python3.6/site-packages/dist2src/worker/updater.py", line 127, in _get_out_of_date_branches
    r = self.cfg.dist_git_svc.call_api(url, params={"with_commits": True})
  File "/usr/lib/python3.6/site-packages/ogr/services/pagure/service.py", line 144, in call_api
    pagure_error=error_msg,
ogr.exceptions.PagureAPIException: Page 'https://git.centos.org/api/0/rpms/bibutils/git/branches' not found when calling Pagure API.
```
even though it's there and should return 200

**Comment by mfocko** [comment]
imo it's something like 502, not sure why they chose 404 and it definitely doesn't make sense to retry 404 :man_shrugging:

**Comment by TomasTomecek** [comment]
404 was just my guess based on the "not found"

also gitlab returns 5xx - we have a bunch of such errors in logs right now

¯\_(ツ)_/¯

**Comment by mfocko** [comment]
i know it's 404, have seen some of the events in Sentry and thought it's the problem with retry mechanism and then noticed it's 404
