### ISSUE TITLE
.git repo not present in the BUILD/ dir after running %prep

### ISSUE THREAD

**Issue by dhodovsk** [packit/dist-git-to-source-git#51]
Known affected packages:

`anaconda-user-help`, `chkconfig`, `cockpit`, `cockpit-appstream`, `corosync-qdevice`, `dotnet`, `elfutils`, `ghostscript`, `gstreamer1-plugins-bad-free`, `gstreamer1-plugins-base`, `gstreamer1-plugins-ugly-free`, `gtk-vnc`, `hwdata, js-d3-flame-graph`, `kmod-kvdo`, `ksc`, `ledmon`, `libblockdev`, `libbpf`, `libmspack`, `libqmi`, `libreoffice`, `libtevent`, `libvma`, `libxkbfile`, `linux-firmware`, `mdevctl`, `mpitests`, `openblas`, `openldap`, `openmpi`, `opensm`, `osinfo-db`, `pmdk-convert`, `redhat-rpm-config`, `redhat-support-lib-python`, `redhat-support-tool`, `resource-agents-sap-hana`, `unbound`, `usermode`, `virt-p2v`, `virtio-win`, `whois`

Convert output:
```
[dhodovsk@shiny playuground]$ podman run --rm -v $PWD:/workdir:z dist2src dist2src -vv convert /workdir/rpms/$PKG:c8s /workdir/src/$PKG:c8s
convert(origin='/workdir/rpms/chkconfig:c8s', dest='/workdir/src/chkconfig:c8s')
Running command get_sources.sh in /workdir/rpms/chkconfig
output = Retrieving https://git.centos.org/sources/chkconfig/c8s/8f80b21c34e9f267feb34766b92acb0cd2932afa

Running rpmbuild in /workdir/rpms/chkconfig
'%setup -q' -> '%autosetup -N'
Traceback (most recent call last):
  File "/usr/local/bin/dist2src", line 11, in <module>
    load_entry_point('dist-git-to-source-git==0.1.dev138+g8e91ba5.d20200909', 'console_scripts', 'dist2src')()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/dist2src/cli.py", line 82, in wrapper
    ret = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/dist2src/cli.py", line 208, in convert
    d2s.convert(origin_branch, dest_branch)
  File "/usr/local/lib/python3.6/site-packages/dist2src/core.py", line 316, in convert
    self.run_prep()
  File "/usr/local/lib/python3.6/site-packages/dist2src/core.py", line 278, in run_prep
    ".git repo not present in the BUILD/ dir after running %prep"
RuntimeError: .git repo not present in the BUILD/ dir after running %prep
```

**Comment by csomh** [comment]
Did you find out why is not present?

**Comment by dhodovsk** [comment]
Not yet, I am still trying to aggregate other failure reports
