### ISSUE TITLE
Architecture is not included: x86_64

### ISSUE THREAD

**Issue by dhodovsk** [packit/dist-git-to-source-git#53]
Affected packages:
`libica`, `libvpd`, `libzfcphbaapi`, `lsvpd`, `opal-prd`, `openssl-ibmca`, `openssl-ibmca`, `powerpc-utils`, `ppc64-diag`

Convert output:
```
convert(origin='/workdir/rpms/libica:c8s', dest='/workdir/src/libica:c8s')
Running command get_sources.sh in /workdir/rpms/libica
output = Retrieving https://git.centos.org/sources/libica/c8s/8192d14867a4f7bf812ef48e830431a5e471270f

Running rpmbuild in /workdir/rpms/libica
This package uses %autosetup or %autopatch.
b'D: created directory(s) /workdir/rpms/libica/BUILD mode 0755'
b'D: created directory(s) /workdir/rpms/libica/RPMS mode 0755'
b'D: created directory(s) /workdir/rpms/libica/SRPMS mode 0755'
b'D: created directory(s) /workdir/rpms/libica/BUILDROOT mode 0755'
b'error: Architecture is not included: x86_64'
b'ufdio:       1 reads,    17154 total bytes in 0.000004 secs'
b'ufdio:       1 reads,     5442 total bytes in 0.000002 secs'
b'ufdio:       1 reads,    17154 total bytes in 0.000003 secs'
Traceback (most recent call last):
  File "/usr/local/bin/dist2src", line 11, in <module>
    load_entry_point('dist-git-to-source-git==0.1.dev138+g8e91ba5.d20200910', 'console_scripts', 'dist2src')()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/dist2src/cli.py", line 82, in wrapper
    ret = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/dist2src/cli.py", line 208, in convert
    d2s.convert(origin_branch, dest_branch)
  File "/usr/local/lib/python3.6/site-packages/dist2src/core.py", line 316, in convert
    self.run_prep()
  File "/usr/local/lib/python3.6/site-packages/dist2src/core.py", line 270, in run_prep
    running_cmd = rpmbuild(*rpmbuild_args)
  File "/usr/local/lib/python3.6/site-packages/sh.py", line 1516, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/usr/local/lib/python3.6/site-packages/sh.py", line 780, in __init__
    self.wait()
  File "/usr/local/lib/python3.6/site-packages/sh.py", line 837, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python3.6/site-packages/sh.py", line 861, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/rpmbuild --nodeps --define '_topdir /workdir/rpms/libica' -bp -vv SPECS/libica.spec

  STDOUT:


  STDERR:
D: created directory(s) /workdir/rpms/libica/BUILD mode 0755
D: created directory(s) /workdir/rpms/libica/RPMS mode 0755
D: created directory(s) /workdir/rpms/libica/SRPMS mode 0755
D: created directory(s) /workdir/rpms/libica/BUILDROOT mode 0755
error: Architecture is not included: x86_64
ufdio:       1 reads,    17154 total bytes in 0.000004 secs
ufdio:       1 reads,     5442 total bytes in 0.000002 secs
ufdio:       1 reads,    17154 total bytes in 0.000003 secs
```

**Comment by dhodovsk** [comment]
For now, ignore these packages that have Exclusive arch other that x86_64
